import type { Metadata } from "next";
import "./globals.css";
import { geist, geistMono, inter } from "./fonts";

export const metadata: Metadata = {
  title: "NextLearn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Removed theme initialization script */}
      </head>
      <body className="antialiased overflow-x-hidden">
        {/* Removed ThemeProvider */}
        <div className="max-w-[100vw] relative overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}