import type { Metadata } from "next";
import "./globals.css";
import { geist, geistMono, inter } from "./fonts";

export const metadata: Metadata = {
  title: "NextLearn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${geistMono.variable} ${inter.variable} antialiased overflow-x-hidden`}
      >
        <div className="max-w-[100vw] relative overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}